version: '2'
services:
  web:
    restart: always
    build: ./server
    ports:
      - "8000:8000"
    links:
      - mysql
    volumes:
      - ./server:/code
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    depends_on:
      - mysql
  
  nginx:
    restart: always
    build: ./client
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - web:web
  
  mysql:
    restart: always
    image: mysql:latest
    volumes:
      - data_sql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD

volumes:
  data_sql:
